### ISSUE TITLE
[Bug]: building package 'swift' on termux docker failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#11110]
### Problem description

building package 'swift' on termux docker failed
<unknown>:0: error: unable to load standard library for target 'aarch64-unknown-linux-android'
[build-log.txt](https://github.com/termux/termux-packages/files/9012751/build-log.txt)

### What steps will reproduce the bug?

build package 'swift'

### What is the expected behavior?

build should succeed

### System information

termux docker on ubuntu 21

**Comment by buttaface** [comment]
Looking at your build log, it fails when building the Swift portion of the compiler itself, my guess is some kind of build race where it needs to cross-compile the stdlib first for Android but doesn't. Can you check if there's anything in the Swift resource directory at `/home/builder/.termux-build/swift/build/swift-android-aarch64/lib/swift/android` where it looks for the Swift stdlib?

**Comment by ALSULTAN** [comment]
builder@322b7ab54702:~/termux-packages$ cd /home/builder/.termux-build/swift/build/swift-android-aarch64/lib/swift/android
builder@322b7ab54702:~/.termux-build/swift/build/swift-android-aarch64/lib/swift/android$ ls -la
total 20
drwxr-xr-x 4 builder builder 4096 Jun 30 15:25 .
drwxr-xr-x 5 builder builder 4096 Jun 30 15:25 ..
drwxr-xr-x 2 builder builder 4096 Jun 30 15:25 aarch64
-rw-r--r-- 1 builder builder 4082 Jun 30 15:25 libswiftCommandLineSupport.a
drwxr-xr-x 2 builder builder 4096 Jun 30 15:26 Swift.swiftmodule
builder@322b7ab54702:~/.termux-build/swift/build/swift-android-aarch64/lib/swift/android$

**Comment by ALSULTAN** [comment]
builder@322b7ab54702:~/.termux-build/swift/build/swift-android-aarch64/lib/swift/android$ find .
.
./Swift.swiftmodule
./Swift.swiftmodule/aarch64-unknown-linux-android.swiftdoc
./Swift.swiftmodule/aarch64-unknown-linux-android.swiftmodule
./Swift.swiftmodule/aarch64-unknown-linux-android.swiftinterface
./aarch64
./aarch64/SwiftGlibc.h
./aarch64/glibc.modulemap
./aarch64/libswiftCommandLineSupport.a
./aarch64/swiftrt.o
./libswiftCommandLineSupport.a
builder@322b7ab54702:~/.termux-build/swift/build/swift-android-aarch64/lib/swift/android$

**Comment by buttaface** [comment]
Huh, I thought adding [this stdlib dependency would make sure it is built first](https://github.com/termux/termux-packages/blob/master/packages/swift/swift-cmake.patch#L88), but it is possible I chose the wrong name and it happened to work most of the time before because the stdlib happened to usually be built first. I will check it and let you know.

**Comment by johndebia2022** [comment]
@buttaface do you have any news?

**Comment by buttaface** [comment]
I looked into it and it appears that while the Swift stdlib is added in the resulting ninja dependency graph as a requirement of building the libswift target (can be seen by running `ninja -t commands libswift`), it is __not__ added as a dependency of building each of the Swift files in libswift (`ninja -t commands libswift/ExperimentalRegex.o`). That works fine in situations like our CI that only has two cores, but in highly parallel builds like yours, where you're running with `-j48`, ninja can apparently schedule those libswift files before the required Swift stdlib is cross-compiled.

I'll look into adding the stdlib dependency for those individual libswift files instead.

**Comment by buttaface** [comment]
I think [this patch should fix the build dependency](https://github.com/buttaface/termux-packages/commit/25fa22ae6064dc7d2b343fa6ee47c8483e5c4edc), try it and let me know.

**Comment by johndebia2022** [comment]
@buttaface still the same issue even after setting 	`TERMUX_MAKE_PROCESSES=1`

**Comment by buttaface** [comment]
OK, I think this should finally do it, buttaface/termux-packages@79aaad870.

**Comment by johndebia2022** [comment]
closed per @buttaface  https://github.com/buttaface/termux-packages/commit/79aaad870.
