### ISSUE TITLE
node sqlite3 package doesn't work

### ISSUE THREAD

**Issue by andy-zhou** [termux/termux-packages#1854]
Steps to recreate:

From fresh Termux:
```
apt install g+ cmake python2 yarn   # Install dependencies
npm config set python $PREFIX/bin/python2.7   # Set python path for node gyp
npm install -g node-gyp   # Install node-gyp globally
npm install sqlite3   # Build sqlite3
node -e "require('sqlite3')"   # failed test
```

I'm using a Asus C302 with Version 62.0.3202.97 (Official Build) (64-bit).

Any ideas?

-Andy

Edit: I forgot to add the error
```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen failed: /data/data/com.termux/files/home/node_modules/sqlite3/lib/binding/node-v57-android-ia32/node_sqlite3.node: has text relocations
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by fornwall** [comment]
> node-v57-android-ia32/node_sqlite3.node: has text relocations

Not knowing much about node modules - is the above file built on device here or downloaded?

**Comment by azhou890** [comment]
Built on the device. My understanding is that when npm can't find specific versions of a a module, it uses node-gyp to build it (which is why g++ and cmake are required).

**Comment by sdrausty** [comment]
https://github.com/npm/npm/issues/19239

**Comment by TAUFEEQ1** [comment]
Try installing python2

**Comment by werlious** [comment]
Fixed, followed the steps from fresh install,  instead of:
npm install sqlite3
Do termux-fix-shebang on $PREFIX/bin/node-pre-gyp and $PREFIX/bin/node-gyp. Build may take a while (20 mins for me) and spit out a lot of warnings

**Comment by Dezyox** [comment]
I'm sorry @werlious, but your command (termux-fix-shebang) don't work because I don't hear how it work, Can you repeat me how to use ? The directory file name is /modmailbot-v2
Thank

**Comment by SoltanDev** [comment]
i followed the steps, but the error the error still appearing

**Comment by KMATTLOG** [comment]
Please termux developers fix that bug

**Comment by TAUFEEQ1** [comment]
Try installing python2

**Comment by twaik** [comment]
Is this issue still reproducible?
