### ISSUE TITLE
termux-tools: libfoo.so is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by kgaughan** [termux/termux-packages#214]
I haven't been able to find any other packages where this is an issue, and nothing in the termux-tools package's ``build.sh`` file jumps out at me as causing the issue.

For some reason, the termux-tools package contains binaries, such as ``df``, ``ping``, &c., that refuse to work on 64-bit ARM devices such as the Nexus 9.

For instance, running ``df`` gives the following error from the linker:

```
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7f874f6010 was not found (block_size=64)
CANNOT LINK EXECUTABLE: "/system/lib/libcutils.so" is 32-bit instead of 64-bit
page record for 0x7fa61ae010 was not found (block_size=32)
```

The output of ``uname -a`` is:

```
Linux localhost 3.10.40-g7949505 #1 SMP PREEMPT Tue Mar 22 19:08:06 uTC 2016 armv8l Android
```

If there's any more information you need, or anything else I can do, I'd be happy to do/provide it.

**Comment by kgaughan** [comment]
Almost forgot! The installed package version is 0.25, which is right up to date.

**Comment by fornwall** [comment]
Thanks! Can you paste the output from `getprop | grep cpu` here?

**Comment by fornwall** [comment]
@kgaughan Also, the output from `sh -x  $PREFIX/bin/df` would be helpful!

**Comment by kgaughan** [comment]
Unfortunately, ``getprop`` is one of the affected binaries. Here's the output:

```
~$ getprop
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7fa313a010 was not found (block_size=64)
~$ sh -x $PREFIX/bin/df
+ getprop ro.product.cpu.abilist64
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7f8068a010 was not found (block_size=64)
+ [ -n  ]
+ BITS=
+ LD_LIBRARY_PATH=/system/lib PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/data/data/com.termux/files/home/projects/go/bin:/system/bin exec /system/bin/df
CANNOT LINK EXECUTABLE: "/system/lib/libcutils.so" is 32-bit instead of 64-bit
page record for 0x7f79fac010 was not found (block_size=32)
```

**Comment by fornwall** [comment]
@kgaughan Hm, interesting! Does `LD_LIBRARY_PATH= getprop` work?

**Comment by kgaughan** [comment]
It indeed does, and I should've thought of that myself!

Here's the output of ``LD_LIBRARY_PATH= getprop | grep cpu``:

```
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
```

It looks like the issue is that it's attempting to load the wrong libraries from ``/data/data/com.termux/files/usr/lib`` then, but when it's loading from ``/system/lib64``, it's fine.

**Comment by fornwall** [comment]
@kgaughan Thanks for the help with this!

The problem was a bit device-spefic in that it varies between devices which libraries are linked in, but hopefully this has been fixed across devices now. Update to the latest version `0.26` of `termux-tools` with an

    apt update && apt upgrade

and let me know how it works!

**Comment by kgaughan** [comment]
That looks to have done the trick! Thanks for your help, and thanks for creating Termux!

**Comment by mirfatif** [comment]
Problem persists on Oreo e.g. tsu and other packages.
`$ tsu -p
CANNOT LINK EXECUTABLE "/su/bin/su": "/system/lib/libdl.so" is 32-bit instead of 64-bit
^CAborted`
It's because tsu uses /system/lib which was I think a symlink to /system/lib64 on my device up to Nougat but now a directory with 32 bit libraries.
`mido:/data/data/com.termux/files/home #
getprop | grep cpu
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]`
