### ISSUE TITLE
[HASKELL] pandoc can not be built with termux-packages

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#23925]
Trying to build pandoc with termux-packages instead of packaging prebuilt version fails with buildscript 
```
TERMUX_PKG_HOMEPAGE=https://pandoc.org/
TERMUX_PKG_DESCRIPTION="Universal markup converter"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.6.4"
TERMUX_PKG_SRCURL=https://github.com/jgm/pandoc/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a343ac43502b699467051948f24f53746d25391c25e3a8dadb30bbd7db313d81
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_BUILD_DEPENDS="ghc-libs"

termux_step_make_install() {
	echo Build complete

	#install -Dm700 "$TERMUX_PKG_BUILDDIR/bin/pandoc" "$TERMUX_PREFIX/bin/pandoc"
	#install -Dm600 "./share/man/man1/pandoc.1.gz" "$TERMUX_PREFIX/share/man/man1/pandoc.1.gz"
	#install -Dm644 /dev/null "$TERMUX_PREFIX"/share/bash-completion/completions/pandoc
}

termux_step_create_debscripts() {
	cat <<-EOF >./postinst
		#!${TERMUX_PREFIX}/bin/sh
		pandoc --bash-completion > ${TERMUX_PREFIX}/share/bash-completion/completions/pandoc
	EOF
}
```
Log 
```
+ cabal build
Resolving dependencies...
Build profile: -w ghc-9.2.5 -O1
In order, the following will be built (use -v for more details):
 - mono-traversable-1.0.21.0 (lib) (requires build)
 - semialign-1.3.1 (lib) (requires build)
 - unicode-collation-0.1.3.6 (lib) (requires build)
 - unix-2.8.6.0 (lib:unix) (requires build)
 - file-io-0.1.5 (lib) (requires build)
 - base-compat-0.14.1 (lib) (requires build)
 - directory-1.3.9.0 (lib:directory) (requires build)
 - th-compat-0.1.6 (lib) (requires build)
 - temporary-1.3 (lib) (requires build)
 - process-1.6.25.0 (lib:process) (requires build)
 - file-embed-0.0.16.0 (lib) (requires build)
 - crypton-x509-store-1.6.10 (lib) (requires build)
 - conduit-1.3.6.1 (lib) (requires build)
 - alex-3.5.2.0 (exe:alex) (requires build)
 - Glob-0.10.2 (lib) (requires build)
 - network-uri-2.6.4.2 (lib) (requires build)
 - typed-process-0.2.12.0 (lib) (requires build)
 - hsc2hs-0.68.10 (exe:hsc2hs) (requires build)
 - crypton-x509-system-1.6.7 (lib) (requires build)
 - libyaml-0.1.4 (lib) (requires build)
 - toml-parser-2.0.1.0 (lib) (requires build)
 - commonmark-extensions-0.2.6 (lib) (requires build)
 - aeson-2.2.3.0 (lib) (requires build)
 - zlib-0.7.1.0 (lib) (requires build)
 - old-time-1.1.0.4 (lib:old-time) (requires build)
 - network-3.2.7.0 (lib:network) (requires build)
 - yaml-0.11.11.2 (lib) (requires build)
 - pandoc-types-1.23.1 (lib) (requires build)
 - ipynb-0.2 (lib) (requires build)
 - doctemplates-0.11.0.1 (lib) (requires build)
 - aeson-pretty-0.8.10 (lib) (requires build)
 - zip-archive-0.4.3.2 (lib) (requires build)
 - JuicyPixels-3.3.9 (lib) (requires build)
 - unix-time-0.4.16 (lib:unix-time) (requires build)
 - streaming-commons-0.2.3.0 (lib) (requires build)
 - socks-0.6.1 (lib) (requires build)
 - iproute-1.7.15 (lib) (requires build)
 - texmath-0.12.9 (lib) (requires build)
 - commonmark-pandoc-0.2.3 (lib) (requires build)
 - conduit-extra-1.3.7 (lib) (requires build)
 - http-client-0.7.19 (lib) (requires build)
 - crypton-x509-validation-1.6.14 (lib) (requires build)
 - xml-conduit-1.10.0.0 (lib:xml-conduit) (requires build)
 - tls-2.1.8 (lib) (requires build)
 - typst-0.7 (lib) (requires build)
 - skylighting-core-0.14.6 (lib) (requires build)
 - pandoc-3.6.4 (lib:xml-light) (first run)
 - citeproc-0.8.1.3 (lib) (requires build)
 - crypton-connection-0.4.3 (lib) (requires build)
 - skylighting-format-typst-0.1 (lib) (requires build)
 - skylighting-format-latex-0.1 (lib) (requires build)
 - skylighting-format-context-0.1.0.2 (lib) (requires build)
 - skylighting-format-blaze-html-0.1.1.3 (lib) (requires build)
 - skylighting-format-ansi-0.1 (lib) (requires build)
 - http-client-tls-0.3.6.4 (lib) (requires build)
 - skylighting-0.14.6 (lib) (requires build)
 - pandoc-3.6.4 (lib) (first run)
Starting     semialign-1.3.1 (lib)
Starting     mono-traversable-1.0.21.0 (lib)
Starting     unix-2.8.6.0 (all, legacy fallback)
Starting     unicode-collation-0.1.3.6 (lib)
Building     mono-traversable-1.0.21.0 (lib)
Building     semialign-1.3.1 (lib)
Building     unicode-collation-0.1.3.6 (lib)
Installing   semialign-1.3.1 (lib)
Completed    semialign-1.3.1 (lib)
Installing   mono-traversable-1.0.21.0 (lib)
Completed    mono-traversable-1.0.21.0 (lib)
Building     unix-2.8.6.0 (all, legacy fallback)
Installing   unix-2.8.6.0 (all, legacy fallback)
Completed    unix-2.8.6.0 (all, legacy fallback)

Failed to build unicode-collation-0.1.3.6.
Build log (
/home/twaik/.cabal/logs/ghc-9.2.5/unicode-collation-0.1.3.6-098b27b8ebf921fe16d59f8d45db01230fb467f81fe1c372178c8964cf6ec0c2.log
):
Configuring library for unicode-collation-0.1.3.6..
Preprocessing library for unicode-collation-0.1.3.6..
Building library for unicode-collation-0.1.3.6..
[ 1 of 10] Compiling Text.Collate.Lang
[ 2 of 10] Compiling Text.Collate.Trie
[ 3 of 10] Compiling Text.Collate.UnicodeData
[ 4 of 10] Compiling Text.Collate.CanonicalCombiningClass
ghc: Couldn't find a target code interpreter. Try with -fexternal-interpreter
Error: cabal: Failed to build unicode-collation-0.1.3.6 (which is required by
pandoc-3.6.4). See the build log above for details.

```
I did not manage haskell packages before so I am not sure what exactly we should do in that case.

**Comment by robertkirkman** [comment]
`pandoc` has been packaged and has been being used, so for example, I believe this issue has been resolved by PRs like this?

- https://github.com/termux/termux-packages/pull/15287

**Comment by robertkirkman** [comment]
never mind, this error actually happens currently when using `scripts/run-docker.sh ./build-package.sh -I -f pandoc`:

```
[4 of 4] Compiling System.Random.SplitMix32 ( src/System/Random/SplitMix32.hs, dist/build/System/Random/SplitMix32.o )
cbits-unix/init.c:7:10: error:
     error: call to undeclared function 'getentropy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        7 |         int r = getentropy(&result, sizeof(uint64_t));
          |                 ^
  |
7 |         int r = getentropy(&result, sizeof(uint64_t));
  |          ^

1 error generated.
`aarch64-linux-android-clang' failed in phase `C Compiler'. (Exit code: 1)
Error: [Cabal-7125]
Failed to build exe:alex from alex-3.5.3.0 (which is required by exe:pandoc from pandoc-cli-3.7.0.2). See the build log above for details.
Failed to build exe:hsc2hs from hsc2hs-0.68.10 (which is required by exe:pandoc from pandoc-cli-3.7.0.2). See the build log above for details.
Failed to build splitmix-0.1.3.1 (which is required by exe:pandoc from pandoc-cli-3.7.0.2). See the build log above for details.
```


It's the same error that there is a patch for working around in:

- https://github.com/termux/termux-packages/pull/25265

This error began relatively recently, and is related to this commit in the haskell splitmix package, adding dependency on `getentropy()`:

https://github.com/haskellari/splitmix/commit/2ef916ac3e6c7bc8c014cc2e0b9b481504f9b803

the haskell splitmix package has stated intent to not support Android, so any changes necessary must be maintained downstream.

Probably it will make the most sense to get the `hledger` package finished first, then copy and paste the final version of its solution for this error into `pandoc`.

**Comment by erplsf** [comment]
I've tried applying my patches to `pandoc` too, and it gets me through building `splitmix` but I'm still getting the same `alex`/`strip` errors. so I have suspicions that [this](https://github.com/termux/termux-packages/pull/24952) PR fixed `shellcheck` but broke `pandoc` package

**Comment by erplsf** [comment]
But let me try actually building `shellcheck` with the current repo.

**Comment by erplsf** [comment]
Yes, `shellcheck` works after applying my `splitmix` patch.

**Comment by MrAdityaAlok** [comment]
This is stale now.
