### ISSUE TITLE
rust analyzer not working as expected

### ISSUE THREAD

**Issue by SegFaulr** [termux/termux-packages#25673]
After recent rust-analyzer update the rust-analyzer doesnot work as before .
heres what is happening in nvim 

- lsp starts and shows errors at first but when i save file   it disappears
- the diagnostics will not show up after but when i save the file it gives me glimpse of diagnostics .

i tried everything. i reinstalled and uninstalled  rust,rust-src,rust-analyzer. i cleared all caches and  maybe it is neovim bug but i could not find related info please help me its really fking my brain right now. i tried to resolve this for more than  4 hours .

**Comment by MohammedKHC** [comment]
I tried to reproduce this bug on my custom Rust IDE, but i failed.
(It uses the latest rust-analyzer from termux-packages)
While the IDE is not free. here is a redeem code for you to get it for free.
D6AP5UTSEMYA0SGXKZGMSP7

Please just tell me if it does work as excepted.

The IDE link: [https://play.google.com/store/apps/details?id=com.mohammedkhc.ide.rust](https://play.google.com/store/apps/details?id=com.mohammedkhc.ide.rust)

**Comment by SegFaulr** [comment]
__

> I tried to reproduce this bug on my custom Rust IDE, but i failed. (It uses the latest rust-analyzer from termux-packages) While the IDE is not free. here is a redeem code for you to get it for free. D6AP5UTSEMYA0SGXKZGMSP7
> 
> Please just tell me if it does work as excepted.
> 
> The IDE link: https://play.google.com/store/apps/details?id=com.mohammedkhc.ide.rust

I tried your ide and rust analyzer works fine there. I really like your editor, so I’ll use it whenever I don’t have my physical keyboard with me. by the way, in your ide's terminal, the block cursor was a bit ahead of the text which might be a bug. I normally use a physical keyboard, so right now I’m running the latest version of rust analyzer from github by compiling it myself.

**Comment by MohammedKHC** [comment]
Thanks for trying it!
If the cursor is a head of the text then i suspect that the terminal  font is not Monospace. Can you please upload a screenshot and tell me if you do use custom fonts. And I will try to investigate further.
Please do so within Bug report screen at the setting of the ide. Since maybe this is getting off topic.
(Also just for the record the ide does use a custom terminal implementation written in kotlin using Jetpack Compose. The terminal emulation is based on Jackpal's terminal. That's because well termux-app is GPL. And my app is closed source.)

**Comment by SegFaulr** [comment]
i donot use any custom fonts

Using JetBrains Mono : 

![Image](https://github.com/user-attachments/assets/fb677e10-4057-4ff4-a9ab-d1320fc0da7d)
Using Monospace :  

![Image](https://github.com/user-attachments/assets/d850b179-8e6c-459b-bf8e-18935c394ec3)

**Comment by rax35** [comment]
I can confirm the same problem on helix. On saving a file, all diagnostic messages from all files disappear. Saving any file again makes them visible for an instant before disappearing again. Other features such as code formatting and go to definition do still work in this state.

**Comment by SegFaulr** [comment]
> I can confirm the same problem on helix. On saving a file, all diagnostic messages from all files disappear. Saving any file again makes them visible for an instant before disappearing again. Other features such as code formatting and go to definition do still work in this state.

true and im glad im not the only one cause  like i was trouble shooting for hours and could not get it to work as expected hope they fix it soon till then im using  a github compiled version.

**Comment by MohammedKHC** [comment]
Seems like that this was an issue on the upstream.
https://github.com/rust-lang/rust-analyzer/issues/20440
It has been fixed.

**Comment by SegFaulr** [comment]
> Seems like that this was an issue on the upstream. [rust-lang/rust-analyzer#20440](https://github.com/rust-lang/rust-analyzer/issues/20440) It has been fixed.

same issue but the termux rust analyzer is not updated yet i dont see any updates and also tried it and its not fixed
