### ISSUE TITLE
zsh: `compinit` is not working

### ISSUE THREAD

**Issue by agguser** [termux/termux-packages#2569]
`autoload -U compinit && compinit` prints function definitions and completely breaks tab completion!

**Comment by fornwall** [comment]
Just to check:

- Does updating to latest packages (running `pkg up` make a difference)?
- Does running in a clean zsh environment (temporarily move away .zshrc perhaps?) make a difference?
- Could you write the output of running `termux-info`?

**Comment by c-e-p-x-u-o** [comment]
I confirm this issue. compinit works fine on desktop with noCaseGlob. But not on termux.

**Comment by c-e-p-x-u-o** [comment]
I've asked on zsh-users@zsh.org maillist:

https://www.zsh.org/mla/users/2018/msg00727.html

**Comment by agguser** [comment]
A workaround is to run `setopt NO_CASE_GLOB` _after_ (not _before_) `autoload -U compinit && compinit`. A year has passed, this issue may be closed now.

**Comment by 532910** [comment]
As you said this is a workaround, not a solution so the issue should remain open until fixed.

**Comment by 532910** [comment]
It look like this has been fixed. Could someone confirm?

**Comment by agguser** [comment]
Still not fixed. Try `setopt NO_CASE_GLOB` before `autoload -U compinit && compinit` in `~/.zshrc`

**Comment by 532910** [comment]
Yep, my fault, still reproducible.
