### ISSUE TITLE
Error in latest Ruby version (2.5.1-1)

### ISSUE THREAD

**Issue by Agent471** [termux/termux-packages#2619]
Error executing gem command:-

$ gem install bundle                             
ERROR:  While executing gem ... (Errno::EINVAL)                 Invalid argument - send(2)
$

https://ibb.co/en2wGo (Screenshot)
OnePlus 3 Android Version 8.1

**Comment by Agent471** [comment]
Please somebody help

**Comment by fornwall** [comment]
This should be fixed in the current `2.5.1-5` version of ruby. Let us know otherwise!

**Comment by James868** [comment]
After updating to latest version of ruby, I can confirm the problem is still there, thank you for the effort to fix it.

**Comment by glfk** [comment]
You can fix it by replacing $PREFIX/lib/ruby/2.x.x/resolv.rb with resolv.rb from ruby package from [cache.ruby-lang.org](cache.ruby-lang.org).
Here's the full log.
![jpg](https://user-images.githubusercontent.com/45167161/49050051-34913780-f214-11e8-845d-307868c33837.jpg)

**Comment by fornwall** [comment]
@glfk So this is still a problem in the latest `2.5.3` version of the ruby package? Do you know what the problem is (what is wrong with resolv.rb)?

**Comment by glfk** [comment]
@fornwall not really sure, im not really understand this such a stuff. Ive been trying to find the solution of this error for 3 days. There is also a case where i "accidently" able to install gem (jekyll at the time), but after i exit the session and trying to install bundler or do "gem update" its give me this error again.

**Comment by glfk** [comment]
@Grimler91 yep
![](https://user-images.githubusercontent.com/45167161/49115104-68c82f00-f2cc-11e8-819f-57bf6b5a3fdc.png)

**Comment by Grimler91** [comment]
Closing (see https://github.com/termux/termux-packages/issues/3380 for latest issue)
