### ISSUE TITLE
mlabel giving error - CANNOT LINK EXECUTABLE "mlabel": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/bin/mtools"...

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#3517]
When I tried using the `mlabel` command I got the following error

> CANNOT LINK EXECUTABLE "mlabel": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/bin/mtools"...

After reading around I saw that others have had this problem and were suggested to downgrade to `libandroid-support.so` version 22. I tried that and I was able to use `mlabe`l without any problem. i was using version 24 when this issue came up.

**Comment by xeffyr** [comment]
What version of `mtools` do you use and what your architecture ?

**Comment by isrgish** [comment]
my arch is aarch64 
Android version 7.0
mtools is version 4.0.23

**Comment by fornwall** [comment]
This should now be fixed in version `4.0.23-1` of the mtools package - run `pkg up` to update!

**Comment by isrgish** [comment]
This issue is still not fixed. The problem doesn't seem to be with `mlabel` just with `libandroid-support.so` as per my original post, if I install the older version of `libandroid-support.so` (22) everything works fine. Its only a problem when I use the newest version(24).

**Comment by xeffyr** [comment]
Fixed. On my Android 6 ARM device it works fine after update.

**Comment by isrgish** [comment]
I'm on Android 7.0 aarch64, I don't know if that should make a difference.

**Comment by Grimler91** [comment]
So which version of mtools do you have installed @isrgis? (`apt show mtools`)

**Comment by isrgish** [comment]
I just did another apt upgrade and its working now.

Something very interesting happened here. I did apt upgrade this morning and all it upgraded was the `libandroid-support.so` and as I mentioned it still wasn't working. Now I decided to try again, now it upgraded 18 different packages and now it is working fine. I'm wondering why it didn't upgrade right away all the packages?
