### ISSUE TITLE
emacsclient can't connect to a running emacs daemon if all Termux sessions have been closed

### ISSUE THREAD

**Issue by sudomain** [termux/termux-packages#4206]
**Problem description**
emacsclient can't connect to a running emacs daemon if all Termux sessions have been closed, then a new session was opened

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.
1. Start an emacs server with or without optional socket name
$ emacs --daemon
or
$ emacs --daemon='sudomain'
2. Close all termux sessions
3. Open termux and verify an emacs daemon is still running
$ pgrep -a emacs
4. try to connect to the daemon using emacsclient
$ emacsclient testfile
or
$ emacsclient -s 'sudomain' testfile

Results in:
emacsclient: can't find socket; have you started the server?

**Expected behavior**

emacsclient should connect to the running daemon even if it was started before closing all termux sessions

**Additional information**
Post output of command `termux-info`.

$ termux-info
Updatable packages:
libiconv/stable 1.16-3 arm [upgradable from: 1.16-2]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.31-perf-g606096e-dirty #1 SMP PREEMPT Tue Jan 17 18:10:20 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
7.0
Device manufacturer:
LGE
Device model:
LGL84VL
$

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Did you expected something else when Termux is closed ?

If you need to keep background processes (e.g. daemon) running, enable wakelock.

**Comment by sudomain** [comment]
It's not that the daemon is stopping when Termux closes. The opposite is happening actually: The daemon is still running after Termux is closed. If the user does ´pgrep emacs` after reopening Termux, they'll see the PID. The thing is, the daemon continues to run but emacsclient can't reconnect. It's as if the daemon process has become unresponsive.

In fact, `emacs --daemon` normally fails if it detects another (unnamed) emacs daemon as shown below:

![Screenshot_2019-08-21-22-09-11](https://user-images.githubusercontent.com/30786326/63480781-2c8fbc80-c461-11e9-94fe-e8333485cdc1.png)

But if Termux is closed and reopened, the even a new daemon doesn't recognize the existence of existing daemons:

![Screenshot_2019-08-21-21-38-47](https://user-images.githubusercontent.com/30786326/63480879-a2942380-c461-11e9-8860-55160f3886d2.png)

If this isn't an issue with emacs --daemon or emacsclient, then please advise how I should handle these unresponsive processes.

**Comment by xeffyr** [comment]
> The opposite is happening actually: The daemon is still running after Termux is closed. 

Ah, the TMPDIR is got wiped. This is actually intended behaviour.
Anyway, running daemons in closed Termux app is **unsupported**.

**Comment by sudomain** [comment]
> running daemons in closed Termux app is unsupported

Ok but there has to be a better way of killing these unresponsive daemons . This is still an issue for 2 reasons:
1.  the daemon allows users to open files (aka "buffers" in emacs terminology), make edits, then disconnect without saving the changes. They could of course reconnect and save  the changes, but if they forget that they had unsaved buffers and they close Termux in the meantime, then those changes are **_lost without warning_** because they daemon became unresponsive.
2. emacs is not known for using little memory. Each of these unresponsive processes take up ~21 MB of virtual memory according to htop. They can build up overtime (as seen in my second screenshot)

**Comment by Grimler91** [comment]
Would be nice to improve this. One way would be to store the daemon stuff in another folder, for emacs --daemon this is fine as it uses [`emacs$(whoami)/server`](https://github.com/termux/termux-packages/blob/c4893382a9ba247efaf45022c6418dd15a284e85/packages/emacs/lisp-server.el.patch.beforehostbuild#L9), so there's no random element in the name. 

This gives a daemon that is persistent over a $TMPDIR clearing:
```bash
TMPDIR=~/.emacs.d/ emacs --daemon
```
and it can then be accessed with:
```bash
emacsclient --socket-name ~/.emacs.d/emacs$(id -u)/server test_file
```

I'm reopening this as I think it's worth improving.

**Comment by Grimler91** [comment]
Sidenote: here's an example how to run `emacs --daemon` as a runit process (i.e. with termux-services): https://hristos.net/emacs-daemon-runit-service/

**Comment by sudomain** [comment]
I made this .bash_logout script before I saw your comment. It's super inelegant, but it starts termux-wake-lock before Termux fully closes. This allows the user to reopen Termux save or discard the modified buffers and shutdown the daemon via (kill-emacs)

`#If we are exiting the last bash process (i.e. The Termux app is closing)
if [ $(pgrep --count 'bash') -eq 1 ]
then
        # If we are exiting and there is atleast 1 emacs daemon running
        if [ $(pgrep --count --full 'emacs --daemon') -ge 1 ]
        then
                #termux-wake-lock will prevent the daemon from becoming unresponsive while Termux closes
                termux-wake-lock
                #notify the user
                termux-notification --id 'emacs-daemon-detection' --vibrate '500' --content '~/.bash_logout detected atleast 1 Emacs daemon.
                Please reconnect using emacsclient, save or discard your buffers, and release the termux-wake-lock'
        fi
fi`

**Comment by tomty89** [comment]
The only issue I see here is that the processes started in Termux might not be killed before it is "swiped away".

**Comment by sudomain** [comment]
Turns out that [the directory in which the socket is created can be controlled via an emacs variable.](https://emacs.stackexchange.com/questions/35949/changing-the-location-of-the-emacs-server-socket/35952#35952) I won't be able to test this for a few hours, but if this works for Termux's version of Emacs, then we have a solution to the socket being deleted when $TMPDIR is cleared.
Short term solution: a change to my ~/.emacs
Long term solution: a change to the default value of this variable for the Termux version of Emacs?

**Comment by Grimler91** [comment]
@tomty89 with swiped away you mean when termux is exited with the exit button

**Comment by Grimler91** [comment]
@sudomain changing server-socket-dir in your .emacs seems like I good idea until we've made a more permanent fix!

**Comment by tomty89** [comment]
@Grimler91 No, I mean from the "recent apps" list, after closing all sessions (either one by one with Ctrl-D or the exit button).

**Comment by sudomain** [comment]
@tomty89 technically I was producing those duplicate unresponsive daemons by exiting all sessions, leaving the recent apps as is (no swiping), then reopening the app/creating a new session. I just did a test to see what happens when Termux is cleared from recent apps as you said and it turns out the daemons get killed.

My elisp skills are very unrefined, but changing the socket-dir works by putting this in my .emacs:

`(setq server-socket-dir "~/.emacs.d")`

and connecting to it works like this:

`emacsclient --socket-name ~/.emacs.d/server FILENAME`

which I'm going to setup as an alias.

It seems that the 2 smaller issues that make up this issue are solved or can be mitigated against:
1.)  The unresponsive daemons issue is fixed by changing the socket to anything but $TMPDIR
2.) User data loss from closing Termux with unsaved buffers open can be mitigated against by executing termux-wake-lock in .bash_logout and warning the user. The example .bash_logout that I posted above might be a good starting point, but I don't like that it assumes termux-api is installed. Should I create a separate issue for this since this one was mainly about the duplicate daemons?

**Comment by tomty89** [comment]
That's why I think the only problem is that, the processes should get killed without the need of the swipe, or, TMPDIR should only be cleaned when Termux is swiped away.

**Comment by Grimler91** [comment]
This is now fixed, `emacs --daemon` now saves the socket to `$PREFIX/var/run/` (unless server-socket-dir has been changed), thanks for reporting!

**Comment by sudomain** [comment]
@Grimler91 thank you for fixing this. I just upgraded emacs and saw the socket being created in $PREFIX/var/run. I think that emacsclient may still be looking forlooking forthe socket in $TMPDIR though. It doesnt find the socket unless I set EMACS_SERVER_FILE to the new location . Should I create a separate issue for this?

**Comment by tomty89** [comment]
I still don't get the fix. So we simply shouldn't expect our TMPDIR to work?

**Comment by Grimler91** [comment]
@sudomain https://github.com/termux/termux-packages/issues/4230 reported this as well so we can use this issue to track the issue

**Comment by Grimler91** [comment]
@tomty89 If we can fix so that TMPDIR is only cleared on device boot (so that no programs that might be using it are running) then we could use $TMPDIR for the sockets. Until then I like this approach.

Alternatively we could make it so that closing all termux sessions kills all background processes, but users might want sshd/mpd/other programs to continue running after exiting termux I think.

A third option would be to never clear TMPDIR, but that probably isn't a good idea either

**Comment by tomty89** [comment]
Why should device boot matter at all? The only problem here is that, TMPDIR should be cleared only when all the processes under Termux are killed.

So either we should make that happen, or get all the processes killed when all the sessions are killed, so that it would be in sync with the clearing of TMPDIR.

Isn't that there's no guarantee the processes will be kept running when all the sessions are killed anyway? That's why we need to enable wake lock for such case.

**Comment by Grimler91** [comment]
> Why should device boot matter at all? The only problem here is that, TMPDIR should be cleared only when all the processes under Termux are killed.

Sure, only be cleared when all processes under termux are killed (or before any processes are started).

> Isn't that there's no guarantee the processes will be kept running when all the sessions are killed anyway? That's why we need to enable wake lock for such case.

I guess this depends on android version/ROM and battery saving settings. I don't have problems with processes being killed on any of my devices

**Comment by xeffyr** [comment]
> or before any processes are started

So we need to revert following:

* https://github.com/termux/termux-app/commit/514f59258a0dd3841a5cdc00480c9055dc12f526

* https://github.com/termux/termux-app/commit/9f79393aa58d67a2e6077d1b4ae93ce33589d8e3

* https://github.com/termux/termux-app/commit/e49d51423631caeda5069d0b77b5599d5b7bc552
