### ISSUE TITLE
screen throws "Bad system call" on Android Pie

### ISSUE THREAD

**Issue by jean** [termux/termux-packages#4414]
**Problem description**
Screen startup shows *Bad system call* message, and screen subsequently terminates.
(Same as https://github.com/termux/termux-packages/issues/3156)

**Steps to reproduce**
Run `screen`.

**Additional information**

```
$ screen --version
Screen version 4.07.00 (GNU) 02-Oct-19
```

```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.14.83-16578333 #2 SMP PREEMPT Mon Aug 19 17:25:58 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-T865
```

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.

```
10-11 22:27:13.749  9493  9493 F libc    : Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP) in tid 9493 (screen), pid 9493 (screen)
10-11 22:27:13.763  9497  9497 F libc    : Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP) in tid 9497 (screen), pid 9497 (screen)
10-11 22:27:13.786  9500  9500 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-11 22:27:13.786  9500  9500 F DEBUG   : Build fingerprint: 'samsung/gts6lxx/gts6l:9/...:user/release-keys'
10-11 22:27:13.786  9500  9500 F DEBUG   : Revision: '8'
10-11 22:27:13.786  9500  9500 F DEBUG   : ABI: 'arm64'
10-11 22:27:13.786  9500  9500 F DEBUG   : pid: 9493, tid: 9493, name: screen  >>> screen <<<
10-11 22:27:13.786  9500  9500 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
10-11 22:27:13.786  9500  9500 F DEBUG   : Cause: seccomp prevented call to disallowed arm64 system call 144
10-11 22:27:13.786  9500  9500 F DEBUG   :     x0  00000000000027dd  x1  0000000000000000  x2  fffffffffffffff4  x3  0000007ba8c1821a
10-11 22:27:13.786  9500  9500 F DEBUG   :     x4  0000007ba8c1822a  x5  0000000000000002  x6  0000000000000030  x7  0000007ff7e356c4
10-11 22:27:13.786  9500  9500 F DEBUG   :     x8  0000000000000090  x9  f1bd6247f5c7a30c  x10 0000000000000000  x11 00000000ffffffff
10-11 22:27:13.786  9500  9500 F DEBUG   :     x12 0000007ff7e356c8  x13 0000000000000000  x14 0000007ff7e356d0  x15 0000000000000001
10-11 22:27:13.786  9500  9500 F DEBUG   :     x16 00000055819efcd0  x17 0000007ba8b84368  x18 0000000000000010  x19 0000005581a04000
10-11 22:27:13.787  9500  9500 F DEBUG   :     x20 0000005581a03ee0  x21 0000000000000000  x22 0000000000002516  x23 0000005581a04000
10-11 22:27:13.787  9500  9500 F DEBUG   :     x24 0000000000000000  x25 00000055819fd168  x26 0000007ff7e37dc9  x27 0000005581a04000
10-11 22:27:13.787  9500  9500 F DEBUG   :     x28 0000005581a04000  x29 0000007ff7e37210
10-11 22:27:13.787  9500  9500 F DEBUG   :     sp  0000007ff7e35e70  lr  0000005581999658  pc  0000007ba8b84370
10-11 22:27:13.788  9500  9500 F DEBUG   : 
10-11 22:27:13.788  9500  9500 F DEBUG   : backtrace:
10-11 22:27:13.788  9500  9500 F DEBUG   :     #00 pc 000000000007d370  /system/lib64/libc.so (setgid+8)
10-11 22:27:13.788  9500  9500 F DEBUG   :     #01 pc 0000000000009654  /data/data/com.termux/files/usr/bin/screen-4.7.0
10-11 22:27:13.798  9501  9501 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by xeffyr** [comment]
Seems like @fornwall deleted my patch: https://github.com/termux/termux-packages/commit/0788922c36ebe7621e3b5c8561321b7f6b079047

**Comment by xeffyr** [comment]
Now it should be fixed. `pkg upgrade`

**Comment by rogerxxxx** [comment]
Ever since this bug was initialized, I've been getting the  bad system call with screen.

I have updated, uninstalled, reinstalled screen, and the bug persists.

**Comment by xeffyr** [comment]
@rogerxxxx It is **fixed** (I don't have bad system call on Pie). Just make sure that your packages are not installed from `termux.net`.

**Comment by rogerxxxx** [comment]
On Android, I simply issue "pkg update" and "pkg upgrade" commands, by default all goes to termux.net.

I do not understand why the main repo would not receive in update/fix when the repo apparently always receives fixes/upgrades.

**Comment by xeffyr** [comment]
`termux.net` is considered as legacy environment and will not receive any updates - https://github.com/termux/termux-packages/issues/4467. It is for Android 5-6 only.

For Android 7+ do `termux-upgrade-repo` for switching.

**Comment by rogerxxxx** [comment]
Thanks.  I understand now the Termux version release cycle is based on Android version utilized, preserving "what works" for people stuck with older Android versions.

**Comment by xeffyr** [comment]
Android versions below Oreo do not require this fix anyway (seccomp filter was introduced in Android 8.0).
