### ISSUE TITLE
Package Request: scipy for python

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#471]
It would be absolutely great if scipy was installable in the python3 environment on Termux. The build instructions are here:

[http://www.scipy.org/scipylib/building/linux.html](http://www.scipy.org/scipylib/building/linux.html)

But the pre-requisites are quite a few (gfortran, LAPACK+ATLAS...) and so it is not trivial to build at all.

Note that many python programs which use scipy could be converted to use only mpmath + numpy (e.g. numpy.fft vs scipy.fftpack, use numpy.frompyfunc() for special functions, e.g. hyp1f1 = np.frompyfunc(mp.hyp1f1,3,1)) but this is much much slower than using scipy. One of my first python programs (solving Moyal Equation for Wigner function using spectral split propagator in Hilbert phase space) runs about 3 times faster with scipy than without it.

Fortunately, mpmath, numpy, sympy and matplotlib all work fine on Termux, so it does qualify as a "pocket scientific workstation" :)

**Comment by its-pointless** [comment]
https://plus.google.com/u/0/108579595606674597667/posts/bAGKg1Htqqg
Some stuff

**Comment by tigran123** [comment]
When trying to install gcc (after "apt remove clang clang-dev") I get this problem:

```
$ dpkg -i gcc_6.1.0-2_aarch64.deb 
(Reading database ... 19999 files and directories currently installed.)
Preparing to unpack gcc_6.1.0-2_aarch64.deb ...
Unpacking gcc (6.1.0-2) ...
dpkg: error processing archive gcc_6.1.0-2_aarch64.deb (--install):
 error creating hard link './data/data/com.termux/files/usr/bin/aarch64-linux-android-gfortran': Permission denied
dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
dpkg-deb: error: subprocess <decompress> returned error exit status 2
Errors were encountered while processing:
 gcc_6.1.0-2_aarch64.deb
```

This is caused by the fact that a non-root cannot create hard links in Android:

```
$ touch a
$ ln a b
$ touch a
$ ln a b
ln: failed to create hard link 'b' => 'a': Permission denied
```

Now, I can try executing it with tsu, but I am not sure if it is safe, i.e. what if dpkg tries to manipulate the files off the real root filesystem rather than those in $PREFIX --- that would wreck my mobile...

**Comment by its-pointless** [comment]
best bet is to just extract it

dpkg -x package.deb ./
That will creat /data/data/com.termux/files/usr/bin/gcc from that dir 

Yeah i fucked up distributing and to be honest you are probably better of not replacing termux apps with that  install cause it might fuck everything up. But there is a doable tool chain there. SO i guess it doesn't matter. I kind of just shared it out of frustration because i can't really do anything more its all way above my pay grade so to speak.

**Comment by tigran123** [comment]
@its-pointless Your striving for perfection is admirable, but let me assure you that the results of your work are not useless --- using the files you distributed speeded up the execution of my python program by a factor of 1.8 (i.e. without scipy it would run much slower by using numpy.fft and mpmath instead). And the results are correct (i.e. I validated them by executing the same program on my desktop).

**Comment by tlnagy** [comment]
Did you all ever get gfortran working on top of termux?

**Comment by its-pointless** [comment]
You asking me? 

The answer is yes.

**Comment by tlnagy** [comment]
Any chance you get submit it as a package to termux? It would be very nice for #702

**Comment by its-pointless** [comment]
it won't happen because android is no longer supporting gcc. Supporting gcc long term to get working correctly everywhere is not worth the investment long term just to get fortran.

**Comment by tlnagy** [comment]
do you know what needs to change in order to port gfortran code over to clang? or is scipy just never going to work on termux?

**Comment by tlnagy** [comment]
Also, would it be possible to build julia inside the docker container mentioned in the readme with gfortran and just ship the binary to termux?

**Comment by its-pointless** [comment]
It works on termux i provide those libraries. Just not going to be supported by fornwall

**Comment by its-pointless** [comment]
after i have lunch i will try. An hour ..
But distributing it means  supporting it... 
there is discussion about outside repos though. That might happen.

**Comment by tlnagy** [comment]
if we could manage to build julia in the docker container we could distribute the binary using fornwall's termux, correct?

**Comment by its-pointless** [comment]
it will work on termux bht not distributed via termux.

**Comment by tlnagy** [comment]
why not?

**Comment by its-pointless** [comment]
because it might not work properly and people will say termux is shit. Distributing only things that work is a good policy.

**Comment by tlnagy** [comment]
Can't we just test it and make sure it works?

**Comment by its-pointless** [comment]
yeah that will help. But not a certainty.

**Comment by asnelt** [comment]
@its-pointless Thanks for bringing scipy to termux! This is awesome. Do you have any address for donations?

**Comment by sudhanshuptl** [comment]
Hi guys.
I am unable to install scipy 
LDFLAGS=" -lm -lcompiler_rt" pip install scipy

Logs:

, line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-u9g68grk/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-szjlo918-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-u9g68grk/scipy/
$

**Comment by its-pointless** [comment]
Scipy requires a fortran compiler which is not available in main repo. But i have made that and a precompileed scipy available in my repo called gcc_termux or its also tells you how to add my repo on the new termux wiki. wiki.termux.com ...

**Comment by remidebette** [comment]
@its-pointless 
Thank you for the repo and for your time. 
On my Samsung S6 Edge the scipy package is not working though...

Here is the error:
```sh
$ packages install scipy
Hit:1 https://its-pointless.github.io/files termux InRelease
Hit:2 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libgfortran4 numpy openblas
The following NEW packages will be installed:
  libgfortran4 numpy openblas scipy
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.5 MB of archives.
After this operation, 69.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://its-pointless.github.io/files termux/extras aarch64 libgfortran4 aarch64 7.1.0-2 [317 kB]
Get:2 https://its-pointless.github.io/files termux/extras aarch64 openblas aarch64 0.2.19-3 [2193 kB]
Get:3 https://its-pointless.github.io/files termux/extras aarch64 numpy aarch64 1.13.1 [2397 kB]
Get:4 https://its-pointless.github.io/files termux/extras aarch64 scipy aarch64 0.19.1-1 [9642 kB]
Fetched 14.5 MB in 6s (2316 kB/s)
Selecting previously unselected package libgfortran4.
(Reading database ... 20019 files and directories currently installed.)
Preparing to unpack .../libgfortran4_7.1.0-2_aarch64.deb ...
Unpacking libgfortran4 (7.1.0-2) ...
Selecting previously unselected package openblas.
Preparing to unpack .../openblas_0.2.19-3_aarch64.deb ...
Unpacking openblas (0.2.19-3) ...
Selecting previously unselected package numpy.
Preparing to unpack .../numpy_1.13.1_aarch64.deb ...
Unpacking numpy (1.13.1) ...
Selecting previously unselected package scipy.
Preparing to unpack .../scipy_0.19.1-1_aarch64.deb ...
Unpacking scipy (0.19.1-1) ...
Setting up libgfortran4 (7.1.0-2) ...
Setting up openblas (0.2.19-3) ...
Setting up numpy (1.13.1) ...
installing numpy
Setting up scipy (0.19.1-1) ...
installing scipy
$
$
$ python
Python 3.6.2 (default, Jul 19 2017, 11:01:41)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import special, optimize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-0.19.1-py3.6-linux-aarch64.egg/scipy/__init__.py", line 114, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-0.19.1-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen failed: "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-0.19.1-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback_c.cpython-36m.so" is 32-bit instead of 64-bit
```

**Comment by its-pointless** [comment]
fixed sorry

**Comment by remidebette** [comment]
It is solved. Thank you.

**Comment by moises-santillan** [comment]
@its-pointless. Thanks a lot for your hard work. I now have numpy, scipy, and matplotlib working on my android phone, which is great. However, I'd very much like to also have them working on my lenovo yoga book, which has a x86_64 architecture. Do you know of any website with instructions to do this? Could you point me to it? Thanks a lot in advance.

**Comment by its-pointless** [comment]
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android
This was my starting point. you need to have ndk with gfortran first so compiling gcc with gfortran openblas for device compiles and works.
There are a few issues minor issues when compiling scipy and numpy on device. And some might exist only on x86.

**Comment by its-pointless** [comment]
If everything works right i should have x86-64 version soon.

**Comment by moises-santillan** [comment]
Thanks a lot. That would be great. I may attempt to do it myself, but I'm
really inexperienced and I'm not sure that I'd be able to do it right.

**Comment by its-pointless** [comment]
iv got x86_64 version of scipy up on my repo. As well as octave gcc-7 etc not everything but a lot.

**Comment by moises-santillan** [comment]
You certainly did it. This is fantastic. Now I have all the programs I need
in termux. Thanks a lot man.

**Comment by moises-santillan** [comment]
@its-pointless. After upgrading numpy to last version in x86_64 it stopped working. I get the following eror message when trying to import numpy within python:

`ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen failed: library "libgcc_s.so.1" not found`

**Comment by its-pointless** [comment]
k i know exactly what happened fixing it shortly

**Comment by its-pointless** [comment]
k should be fixed

**Comment by moises-santillan** [comment]
@its-pointless. Sorry I upgraded both numpy and scipy, but still get the same error while trying to import them.

**Comment by its-pointless** [comment]
Update now ... should mean you get a fixed libgfortran... should work then

**Comment by its-pointless** [comment]
This is what happens when im messing around with compilers. Sorry

**Comment by moises-santillan** [comment]
@its-pointless. All works well now. Thanks a lot for your prompt response and for dealing with these issues so efficiently.

**Comment by anupamsingh81** [comment]
Scipy installs but following error on importing..



Earlier before adding ur repo had installed numpy 1.12 by this 

LDFLAGS=" -lm -lcompiler_rt" pip install  numpy==1.12 ,numpy works well with 1.12




most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.0.0-py3.6-linux-aarch64.egg/scipy/__init__.py", line 118, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.0.0-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen failed: library name "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.0.0-py3.6-linux-aarch64.egg/scipy/_lib/_ccallback_c.cpython-36m.so" too long

Even if I do pkg install scipy numpy it throws error on importing

**Comment by Grimler91** [comment]
@anupamsingh81 try installing numpy from its-pointless repo as well, i.e. uninstall numpy 1.12 first (`pip uninstall numpy`) and then install numpy from the repo with `pkg install numpy`.

**Comment by anupamsingh81** [comment]
Following error on reinstalling as per your instructions
Setting up numpy (1.13.3-2) ..
$ python
Python 3.6.4 (default, Jan  7 2018, 03:52:16)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for
>>> import numpy as np
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen failed: library name "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/core/multiarray.cpython-36m.so" too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen failed: library name "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.3-py3.6-linux-aarch64.egg/numpy/core/multiarray.cpython-36m.so" too long

>>>

**Comment by Grimler91** [comment]
@anupamsingh81 Alright, then the error is what it says that it is, the path to the file is too long. 

The same issue is described in https://github.com/termux/termux-app/issues/213, seems to be isolated to android 5.
You could perhaps work around it by moving the .so file (and any other libraries giving the same error) to `$PREFIX/lib/` instead.

**Comment by Grimler91** [comment]
I have an arm device with android 5.0.2 but I can't reproduce the issue (I have installed a custom rom though, it might have been fixed in that rom I suppose). Or maybe it's only on aarch64 with android<6

**Comment by kragens** [comment]
I got following error with numpy with android 8

` python
Python 3.8.0 (default, Nov 17 2019, 21:52:46) 
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen failed: cannot locate symbol "__aeabi_f2ulz" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/_multiarray_umath.cpython-38.so"...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/data/data/com.termux/files/usr/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
`

**Comment by landfillbaby** [comment]
it simply needs to be rebuilt for python 3.9, the one you installed was built for 3.8

**Comment by jinlin82** [comment]
@landfillbaby i have the same problem, how can I rebuild scipy for the new python 3.9 or how can I install old python 3.8? thanks

**Comment by asnelt** [comment]
It was built for Python 3.9 and needs to be rebuild for Python 3.10.

**Comment by nikey02** [comment]
> It was built for Python 3.9 and needs to be rebuild for Python 3.10.

If scipy 1.6.3 is compatible with 3.10 python 
U can just edit .deb file and change path to `3.9 to 3.10`

Or 
Install scipy from its-pointless repo and manually 
Change its path deb just contains .egg file 

Or 

Build it userself on device

**Comment by asnelt** [comment]
Here is what worked for me:
```bash
# Set up the its-pointless repository according to https://github.com/its-pointless/gcc_termux
# Eventually remove previous NumPy and SciPy installations
apt remove --purge numpy scipy
# Install and setup build tools
apt install python build-essential clang gcc-11
setupclang-gfort-11
# install blas and set environment variables
apt install openblas
export BLAS=/data/data/com.termux/files/usr/lib/libblas.so
export LAPACK=/data/data/com.termux/files/usr/lib/liblapack.so
export CC=clang
export CPP=clang++
# Install wheel, NumPy and SciPy via pip
pip install wheel
pip install numpy
pip install scipy
```
It could be that some build dependency package is missing here as I already had a build environment on my device. It takes a while to build and you need enough memory on your device for the build to succeed.

**Comment by xloem** [comment]
@its-pointless are you aware that python3 has been upgraded to 3.10?

**Comment by SamYokai** [comment]
> Here is what worked for me:
> 
> ```shell
> # Set up the its-pointless repository according to https://github.com/its-pointless/gcc_termux
> # Eventually remove previous NumPy and SciPy installations
> apt remove --purge numpy scipy
> # Install and setup build tools
> apt install python build-essential clang gcc-11
> setupclang-gfort-11
> # install blas and set environment variables
> apt install openblas
> export BLAS=/data/data/com.termux/files/usr/lib/libblas.so
> export LAPACK=/data/data/com.termux/files/usr/lib/liblapack.so
> export CC=clang
> export CPP=clang++
> # Install wheel, NumPy and SciPy via pip
> pip install wheel
> pip install numpy
> pip install scipy
> ```
> 
> It could be that some build dependency package is missing here as I already had a build environment on my device. It takes a while to build and you need enough memory on your device for the build to succeed.

wow, this look nice, but I follow also doesn't work, maybe version problem? Also, want to try ask that in my Python version is 3.8.0 and why the scipy I installed through pkg install is scipy_1.3.0? By the way my ternux is 0.75 and android 5.1.1

**Comment by SamYokai** [comment]
@its-pointless 
sorry for asking, Im new for using this and want to install scipy in android 5.1.1, but I'm not really understand what step should I do in the instruction, because I also new in doing linux platform so a bit confuse, is it possible that need your help to explain step by step to setup? if can setup your repo and install through pip will more better since actually I had try a bit and pkg install success but not show in pip list so cannot import it. But also just asking, since there have limitation on the device Im using, or other have another suggestion or opinion also can share with me. Thanks.

**Comment by xtkoba** [comment]
its-pointless is gone, I suppose.

**Comment by SamYokai** [comment]
> 

I also dont know, haha, but now I had did for scipy. Then new problem is opencv, follow the step but also cannot found in pip list although I pkg install opencv.

**Comment by SunPodder** [comment]
Package: `python-scipy` in [TUR](https://github.com/termux-user-repository/tur)

@xtkoba completed

**Comment by licy183** [comment]
`flang-new` (a.k.a `llvm-flang`) has been bumped to 16 recently, and I can confirm that scipy is able to be compiled on device (at least for aarch64). See https://github.com/termux/termux-packages/pull/15856#issuecomment-1487241711.

But I'd like to keep this issue open because compiling scipy is quite time-costing. Maybe when NDK toolchian uses llvm16 (NDK 26 will use), we will be able to compile a custom fortran toolchain for Android and compile this package.

**Comment by Ammar-Husain** [comment]
So right now isn't thers is anyway to use scipy in termux ? i need it to install scikit-learn

**Comment by Ammar-Husain** [comment]
I have install scipy from it's pointless repo but now it is installed in termux but can't import it in python files and it is not showing in pip

**Comment by Ammar-Husain** [comment]
I have install scipy from it's pointless repo but now it is installed in termux but can't import it in python files and it is not showing in pip

**Comment by licy183** [comment]
`python-scipy` in pointless repo is compiled for older python, not for python 3.11. `python-scipy` is packaged in TUR now, and can be installed through `pkg install tur-repo && pkg install python-scipy`.

If you really need to compile it from source please follow the steps in https://github.com/termux/termux-packages/pull/15856#issuecomment-1487241711.

**Comment by Ammar-Husain** [comment]
> 

I had tried to install `python-scipy` from TUR but it hadn't work before because it was conflicting with the `scipy` package from it's pointles repo but now after i uninstall it's pointless `scipy`, `python-scipy` have installed perfectly and everything is working now, Thank you !.

**Comment by Ammar-Husain** [comment]
> 

I had tried to install `python-scipy` from TUR but it hadn't work before because it was conflicting with the `scipy` package from it's pointles repo but now after i uninstall it's pointless `scipy`, `python-scipy` have installed perfectly and everything is working now, Thank you !.
