### ISSUE TITLE
error with package calc

### ISSUE THREAD

**Issue by ulph0** [termux/termux-packages#6395]
i installed package calc (2.12.7.6 arm) on lineageos 17.1/android 10
when i try to start calc, instead of going into iteractive mode, calc enerates the error message
"Exponent to large"

**Steps to reproduce**
- pkg install calc
- calc

**Expected behavior**
go into interactive mode if no arguments are omitted.

**Additional information**

`ackages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://ipfs.sloppyta.co/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.4.113-lineageos-gf6e14b9 #1 SMP PREEMPT Sun Feb 7 05:25:22 UTC 2021 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G900F``

```

**Comment by Grimler91** [comment]
I suppose error only happens on arm, seem to work on aarch64

**Comment by Grimler91** [comment]
2.12.8.0 was released yesterday. I pushed an update to add it to the repo so in ~15 minutes or so you should be able to `pkg upgrade` to get it.

Could you check if the latest version fixes the issue?

**Comment by calheiros** [comment]
@Grimler91 No, same message.

**Comment by ulph0** [comment]
I did that but sorry, still get "Exponent to large" both when i try to start interactive mode with just executing 'calc' and in non-interactive mode by starting it with a problem like 'calc 2/3'.

**Comment by xtkoba** [comment]
Probably we have to define `LONG_BITS` manually. For 32-bit archs:
```
--- ./Makefile.ship.orig
+++ ./Makefile.ship
@@ -141,8 +141,8 @@
 #
 # Select LONG_BITS= 32 for DJGPP.
 #
-LONG_BITS=
-#LONG_BITS= 32
+#LONG_BITS=
+LONG_BITS= 32
 #LONG_BITS= 64
 
 # Determine if we have the ANSI C fgetpos and fsetpos alternate interface
```

I don't come up with how to do it appropriately for both 32-bit and 64-bit archs.
