### ISSUE TITLE
Unable to install php in termux

### ISSUE THREAD

**Issue by AKTOOL** [termux/termux-packages#6770]
When i tried to install php in termux. By command pkg install php or apt install php then it shows

$apt install php
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php' has no installation candidate

How do i solve this...

**Comment by RossComputerGuy** [comment]
Are you using the old repositories? #6726

**Comment by Grimler91** [comment]
Should be fixed now, `apt update && apt install php` should work. php for other arches than i686 was missing for some reason

**Comment by mauro199304** [comment]
I have followed the steps and I still cannot update pkg upgrade error, from today I get that error.  Please, what else can I do?

**Comment by mauro199304** [comment]
when installing with that command it tells me this message: apt update && apt install php ...help
The following packages have unmet dependencies:
 libgd : Depends: libjpeg-turbo but it is not installable
         Depends: libtiff but it is not installable
         Depends: libwebp but it is not going to be installed
E: Unable to correct problems, you have held broken package
