### ISSUE TITLE
su binary not found

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#723]
Everytime I try to get root permission it shows error like ==>

No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.

Even though I have root...
Plz fix it ..
Thanks

**Comment by fornwall** [comment]
Do you know where your `su` binary is? Could you run `which su` in e.g. [Terminal emulator for Android](https://play.google.com/store/apps/details?id=jackpal.androidterm&hl=en) and report the result here?

**Comment by Auxilus** [comment]
It's /data/data/com.termux/files/usr/bin/su

**Comment by Auxilus** [comment]
/system/bin/su

**Comment by fornwall** [comment]
@Auxilus Thanks! This should be fixed in version 0.36 of the termux-tools package, to which you can update with:

    apt update && apt upgrade

**Comment by jeremyburr** [comment]
I'm having the same issue. "apt update && apt upgrade " does not fix. "which su" prints: "/data/data/com.termux/files/usr/bin/su". Was working fine last week. Suggestions, anyone?

**Comment by jeremyburr** [comment]
Ah, it appears updating my OS (Oxygenos) removed my root access. Perhaps I just need to re-root...

**Comment by thaizin** [comment]
Please some one help me root funtouch os with termux but while giving tsu ..permission is denied or operation not permitted

**Comment by sdrausty** [comment]
@thaixin have you tried proot?

**Comment by anujraj1875** [comment]
$ su
No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.
$

**Comment by DavidLuna98** [comment]
Yo tengo el mismo problema hasta ahora, aun que lo vuelva a rootear sigue con lo mismo.

**Comment by bbls9ui** [comment]
Help
