### ISSUE TITLE
mutt can't open editor

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#84]
When I try to send or reply to a mail with mutt I get the following error:
Error running "vim '/data/data/com.termux/files/usr/tmp/mutt-localhost-10130-9969-6589763391732300340'"!

Error running "nano '/data/data/com.termux/files/usr/tmp/mutt-localhost-10130-9969-6589763391732300340'"!

This happens with any editor.

**Comment by fornwall** [comment]
Hi, try

    apt update && apt upgrade

to install an updated version (`1.5.24-1`) which should fix the problem (as well as building with header cache functionality enabled and fixing some crashes). Let me know if it works and if anything else is broken in the mutt package!

**Comment by Neo-Oli** [comment]
Hi. Opening the editor works now thanks. I am however still unable to send mails with gmail. I get the following error: "SMTP authentication requires SASL". I read that USE_SASL needs to be specified during compilation.
